import { Router, Response } from 'express';
import { prisma } from '../prisma.js';
import { authenticate, AuthenticatedRequest } from '../middleware/auth.js';
import { AuditService } from '../services/audit.service.js';

export const siemRouter = Router();

siemRouter.use(authenticate);

// Educational simulation events
const SIMULATED_EVENTS = [
  {
    id: 'evt-001',
    eventType: 'AUTH_BRUTE_FORCE_BURST',
    severity: 'HIGH',
    source: 'Edge WAF / Identity Gateway',
    description: '142 consecutive failed authentication attempts against root/admin from ASN 14061.',
    mitreTechnique: 'T1110 - Brute Force',
    isSimulated: true,
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    status: 'NEW',
    ip: '198.51.100.44',
  },
  {
    id: 'evt-002',
    eventType: 'SUSPICIOUS_PARENT_PROCESS',
    severity: 'CRITICAL',
    source: 'SEC-HQ-WIN11-042 (EDR)',
    description: 'Microsoft Word spawned powershell.exe with encoded argument string.',
    mitreTechnique: 'T1059.001 - PowerShell Execution',
    isSimulated: true,
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    status: 'INVESTIGATING',
    ip: '10.240.12.84',
  },
  {
    id: 'evt-003',
    eventType: 'METADATA_API_PROBING',
    severity: 'MEDIUM',
    source: 'PROD-K8S-NODE-03 (Cloud EDR)',
    description: 'Pod container queried cloud metadata service IP 169.254.169.254 for IAM role tokens.',
    mitreTechnique: 'T1552 - Unsecured Credentials',
    isSimulated: true,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    status: 'NEW',
    ip: '10.240.45.19',
  },
  {
    id: 'evt-004',
    eventType: 'OUTBOUND_DNS_BEACONING',
    severity: 'HIGH',
    source: 'Internal Recursive DNS',
    description: 'Periodic TXT query burst to dynamic domain *.ns-sync-zone.org every 30.05 seconds.',
    mitreTechnique: 'T1071.004 - DNS Command and Control',
    isSimulated: true,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    status: 'NEW',
    ip: '10.240.12.84',
  },
  {
    id: 'evt-005',
    eventType: 'MFA_PUSH_SPAM_CHALLENGE',
    severity: 'MEDIUM',
    source: 'Identity Provider (Okta/Entra)',
    description: 'User r.chen denied 4 consecutive push notifications within 90 seconds.',
    mitreTechnique: 'T1621 - Multi-Factor Authentication Request Generation',
    isSimulated: true,
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    status: 'RESOLVED',
    ip: '203.0.113.88',
  },
  {
    id: 'evt-006',
    eventType: 'AUDIT_LOG_EXPORT_TRIGGERED',
    severity: 'INFO',
    source: 'CYBERGUARD IAM Subsystem',
    description: 'Scheduled weekly compliance log archive generated by automated backup worker.',
    mitreTechnique: 'T1005 - Data from Local System',
    isSimulated: true,
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    status: 'RESOLVED',
    ip: '127.0.0.1',
  },
];

/**
 * GET /api/siem/events
 */
siemRouter.get('/events', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  const mode = req.query.mode as string;
  const isSimulation = mode === 'simulation';

  let liveEvents: any[] = [];
  try {
    liveEvents = await prisma.securityEvent.findMany({
      where: { isSimulated: false },
      orderBy: { createdAt: 'desc' },
      take: 50,
    });
  } catch {
    // DB empty or not running
  }

  const hasLive = liveEvents.length > 0;

  if (!hasLive && !isSimulation) {
    res.json({
      telemetryState: 'NO DATA',
      statusMessage: 'No live SIEM log collector connected. Switch to Simulation mode for educational walkthrough.',
      events: [],
      stats: {
        total: 0,
        critical: 0,
        high: 0,
        medium: 0,
        low: 0,
        info: 0,
      },
    });
    return;
  }

  const events = isSimulation ? SIMULATED_EVENTS : liveEvents;

  const stats = {
    total: events.length,
    critical: events.filter((e) => e.severity === 'CRITICAL').length,
    high: events.filter((e) => e.severity === 'HIGH').length,
    medium: events.filter((e) => e.severity === 'MEDIUM').length,
    low: events.filter((e) => e.severity === 'LOW').length,
    info: events.filter((e) => e.severity === 'INFO').length,
  };

  res.json({
    telemetryState: isSimulation ? 'SIMULATION' : 'LIVE DATA',
    statusMessage: isSimulation 
      ? 'SIMULATION MODE: Displaying synthetic enterprise attack chain scenarios for educational triage.'
      : 'LIVE DATA: Real-time SIEM event collection pipeline active.',
    events,
    stats,
  });
});

/**
 * POST /api/siem/copilot-analysis
 * Security Analyst Copilot provides defensive summarization and remediation steps
 */
siemRouter.post('/copilot-analysis', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  const { eventId, eventTitle, severity, mitreTechnique, source, description, isSimulated } = req.body;

  // Defensive remediation mapping based on MITRE technique & severity
  const remediationDatabase: Record<string, { summary: string; containment: string[]; eradication: string[]; recovery: string[] }> = {
    'T1059.001 - PowerShell Execution': {
      summary: 'Potential malicious script execution spawned by an office process. Indicates living-off-the-land (LotL) execution or dropper activity.',
      containment: [
        'Isolate host SEC-HQ-WIN11-042 via EDR network containment immediately.',
        'Terminate child processes with PID 4892 and any active spawned threads.',
        'Dump process memory of powershell.exe before reboot to extract decrypted command strings.',
      ],
      eradication: [
        'Inspect parent Word document in email gateway to identify original sender/phishing campaign.',
        'Check persistent scheduled tasks and registry Run keys (HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run).',
        'Revoke active SSO sessions for user account on that workstation.',
      ],
      recovery: [
        'Re-image host if unapproved persistence mechanisms are detected.',
        'Enable ConstrainedLanguage mode for PowerShell across non-admin GPOs.',
        'Verify host endpoint AV/EDR signatures are updated.',
      ],
    },
    'T1110 - Brute Force': {
      summary: 'Automated credential stuffing or dictionary attack targeting administrative endpoints.',
      containment: [
        'Verify WAF IP rate limiting and block offending ASN at perimeter edge.',
        'Force MFA challenge for targeted accounts.',
        'Verify accounts have not been successfully authenticated from foreign IP ranges.',
      ],
      eradication: [
        'Rotate passwords for accounts with high failed attempt volumes.',
        'Disable public direct login to administration consoles; enforce VPN/Bastion with Zero Trust.',
      ],
      recovery: [
        'Review audit logs for any rogue tokens created during the burst period.',
        'Confirm geo-blocking and bot detection thresholds are active on Cloudflare/WAF.',
      ],
    },
    'T1552 - Unsecured Credentials': {
      summary: 'Instance metadata querying inside Kubernetes pod suggests SSRF or unauthorized pod access attempting IAM role assumption.',
      containment: [
        'Apply IMDSv2 hop-limit = 1 on underlying EC2 instances to prevent containerized SSRF egress.',
        'Isolate affected pod container PROD-K8S-NODE-03 via network policy.',
      ],
      eradication: [
        'Audit IAM role permissions attached to the node; remove over-privileged wildcard policies.',
        'Inspect container web application code for unvalidated URL redirection or proxy endpoints.',
      ],
      recovery: [
        'Enforce Calico/Cilium egress policy denying 169.254.169.254 except for approved daemonsets.',
      ],
    },
  };

  const defaultRemediation = {
    summary: `Defensive triage for security event: ${eventTitle || 'Telemetry Alert'}. Severity assessed as ${severity || 'MEDIUM'}.`,
    containment: [
      'Validate if the observed behavior aligns with authorized administrative workflows or maintenance windows.',
      'Check firewall egress logs and DNS resolvers for concurrent unusual connections.',
    ],
    eradication: [
      'Audit file system changes and user privilege alterations around the event timestamp.',
      'Scan host with updated endpoint protection engine.',
    ],
    recovery: [
      'Document findings in incident ticket and monitor telemetry for recurrence.',
    ],
  };

  const matched = (mitreTechnique && remediationDatabase[mitreTechnique]) || defaultRemediation;

  await AuditService.log({
    actorId: req.user!.id,
    actorEmail: req.user!.email,
    action: 'COPILOT_ANALYSIS_REQUESTED',
    entityType: 'SecurityEvent',
    entityId: eventId,
    ipAddress: req.ip || '127.0.0.1',
    userAgent: req.headers['user-agent'] || 'Unknown',
    details: { eventId, isSimulated },
  });

  res.json({
    copilotAnalysis: {
      eventId,
      dataMode: isSimulated ? 'SIMULATION' : 'LIVE DATA',
      disclaimer: isSimulated 
        ? 'NOTE: This analysis applies to simulated training telemetry and must not be treated as a live incident response.'
        : 'LIVE DATA INCIDENT: Execute containment procedures under SOC standard operating guidelines.',
      executiveSummary: matched.summary,
      containmentSteps: matched.containment,
      eradicationSteps: matched.eradication,
      recoverySteps: matched.recovery,
      mitreAttAndCk: {
        technique: mitreTechnique || 'T1082 - System Information Discovery',
        tactic: 'Defensive Mitigation Strategy (NIST SP 800-61 Rev. 2)',
      },
    },
  });
});
